config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  
  resources :transactions
  resources :listings do
  resources :orders, only: [:new, :create]  
  end  

  get 'users/auth/facebook/callback', to: "sessions#create"
  get 'users/auth/facebook/signout', to: "sessions#destroy"

  get 'pages/about'

  get 'pages/contact'
  get 'sales' => "orders#sales"
  get 'purchases' => "orders#purchases"
  get 'dashboard' => "orders#dashboard"
  get 'pages/home'
  get 'seller' => "listings#seller"

 get 'get_info', to: 'books#get_info', path: "/books/new/get_info"

  root 'listings#index'

end

app/models/listing.rb
class Listing < ActiveRecord::Base

mount_uploader :image, ImageUploader

	validates :name, :description, :price, presence: true
	validates :price, numericality: { greater_than: 0 }
belongs_to :user
has_many :orders
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy, :seller]
  before_filter :check_user, only: [:edit, :update, :destroy]

  # GET /listings
  # GET /listings.json
  def index
    @listings = Listing.all.order("created_at DESC" )
  end

  def seller
   @listings = Listing.where(user: current_user).order("created_at DESC" )

  end


  # GET /listings/1
  # GET /listings/1.json
  def show
  end

  # GET /listings/new
  def new
    @listing = Listing.new
  end

  # GET /listings/1/edit
  def edit
  end

  # POST /listings
  # POST /listings.json
  def create
    @listing = Listing.new(listing_params)
    @listing.user_id = current_user.id

    
    respond_to do |format|
      if @listing.save
        format.html { redirect_to @listing, notice: 'Listing was successfully created.' }
        format.json { render :show, status: :created, location: @listing }
      else
        format.html { render :new }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /listings/1
  # PATCH/PUT /listings/1.json
  def update
    respond_to do |format|
      if @listing.update(listing_params)
        format.html { redirect_to @listing, notice: 'Listing was successfully updated.' }
        format.json { render :show, status: :ok, location: @listing }
      else
        format.html { render :edit }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listings/1
  # DELETE /listings/1.json
  def destroy
    @listing.destroy
    respond_to do |format|
      format.html { redirect_to listings_url, notice: 'Listing was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listing
      @listing = Listing.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def listing_params
      params.require(:listing).permit(:name, :description, :price, :availability, :image)
    end

   def check_user
      if current_user != @listing.user
        redirect_to root_url, alert: "Sorry, this listing belongs to someone else"
      end
    end

end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/listings/_form.html.erb
<%= form_for(@listing, :html => { multipart: true }) do |f| %>
  <% if @listing.errors.any? %>
    
    <div id="error_explanation" class= "alert alert-warning alert-dismissible container" role="alert">
       <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>  
      <h4><%= pluralize(@listing.errors.count, "error") %> prohibited this listing from being saved:</h4>

      <ul>
      <% @listing.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>


  <% end %>

<div class="container" >

  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_area :description, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :price %><br>
    <%= f.text_field :price, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :availability %><br>
    <%= f.check_box :availability, class: "form-control" %>
  </div>

 <div class="form-group">
    <%= f.label :image %><br>
    <%= f.file_field :image, class: "form-control" %> 
  </div>
  
  <div class="actions">
    <%= f.submit class: "btn btn-primary" %>
  </div>

</div>

<% end %>

app/views/listings/edit.html.erb
<h1 class= "text-center">Editing Listing</h1>

<%= render 'form' %>

<%= link_to 'Show', @listing, class: "btn btn-link" %> |
<%= link_to 'Back', listings_path, class: "btn btn-link" %>

app/views/listings/index.html.erb
<div class="jumbotron container">
  <h1>Shariends</h1>
  <p></p>
</div>


<div class="row">
  <% @listings.each do |listing| %>
    <div class="col-md-3">
      <div class="thumbnail">
        <%= link_to image_tag(listing.image_url(:thumb)), listing_path(listing) %>

        <div class="caption text-center">
          <h3><%= listing.name %></h3>

          <p><%= number_to_currency(listing.price, precision: 1) %></p>
          <h5> <%= "Sold by #{listing.user.name} - posted #{time_ago_in_words(listing.created_at)}" %> </h5>
         
               <% if (user_signed_in?) && (current_user == listing.user) %>
              <%= link_to 'Edit', edit_listing_path(listing), class: "btn btn-primary" %>
              <%= link_to 'Destroy', listing, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-warning" %>
            <% end %>

        </div>
      </div>
    </div>
  <% end %>
</div>

<br>

<br>
<% if user_signed_in? %>
<%= link_to 'New Listing', new_listing_path %>
<% end %>

app/views/listings/new.html.erb
<h1 class= "text-center">New Listing</h1>

<%= render 'form' %>

<%= link_to 'Back', listings_path %>

app/views/listings/seller.html.erb
<div class="container-fluid">

<div class="row">

<div class="col-md-6"> <div class="text-center"> Selling </div>

<table class="table table-striped table-bordered">
  <tr>
    <th class="center">Image</th>
    <th class="center">Name</th>
    <th class="center">Availability</th>
    <th class="center">Price</th>
    <th class="center">Action</th>
  </tr>

<% @listings.each do |listing| %>
    <tr>
      <td><%= image_tag listing.image.url(:thumb) %></td>
      <td><%= listing.name %></td>
      <td><%= listing.availability %></td>
      <td><%= number_to_currency(listing.price) %></td>
       <td>
        <div class="btn-group">
          <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
            Action <span class="caret"></span>
          </button>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to "View", listing, class: "btn btn-link" %></li>
            <li><%= link_to "Edit", edit_listing_path(listing), class: "btn btn-link" %></li>
            <li><%= link_to 'Destroy', listing, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-link" %></li>
          </ul>
        </div>
      </td>
    </tr>
  <% end %>
</table>



</div>

<div class="col-md-6">Purchased
<div class="row">
  <div class="col-md-4">.col-md-4</div>
  <div class="col-md-4">.col-md-4</div>
  <div class="col-md-4">.col-md-4</div>
</div>


</div>

</div>
</div>


<br>
<% if user_signed_in? %>
<%= link_to 'New Listing', new_listing_path %>
<% end %>

app/views/listings/show.html.erb
<div class="row">
  <div class="col-md-6">
    <div class="thumbnail">
      <%= image_tag @listing.image_url %>
    </div>
  </div>
  <div class="col-md-6">
    <h3><%= @listing.name %></h3>
    <p><%= @listing.price %></p>
    <p><%= @listing.description %></p>
    <p><%= @listing.availability %></p>
  </div>
</div>

 <div class="center">
      <%= link_to "Buy It Now", new_listing_order_path(@listing), class: "btn btn-primary" %>
    </div>


<% if current_user == @listing.user %>
<%= link_to 'Edit', edit_listing_path(@listing) %> |
<% end %>
<%= link_to 'Back', listings_path %>