config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  
  resources :transactions
  resources :listings do
  resources :orders, only: [:new, :create]  
  end  

  get 'users/auth/facebook/callback', to: "sessions#create"
  get 'users/auth/facebook/signout', to: "sessions#destroy"

  get 'pages/about'

  get 'pages/contact'
  get 'sales' => "orders#sales"
  get 'purchases' => "orders#purchases"
  get 'dashboard' => "orders#dashboard"
  get 'pages/home'
  get 'seller' => "listings#seller"

 get 'get_info', to: 'books#get_info', path: "/books/new/get_info"

  root 'listings#index'

end

app/models/order.rb
class Order < ActiveRecord::Base
  validates :address, :city, :state, presence: true

##stuk.io
#OrderごとにユニークなIDを発行
before_create :populate_guid

  belongs_to :listing
#buyer/sellerがそれぞれUserクラスに属することを定義
  belongs_to :buyer, class_name: "User"
  belongs_to :seller, class_name: "User"


##stuk.io

 private
 
  def populate_guid
     self.guid = SecureRandom.uuid()
  end


end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /orders
  # GET /orders.json

  def sales
    @orders = Order.all.where(seller: current_user).order("created_at DESC")
  end

  def purchases
    @orders = Order.all.where(buyer: current_user).order("created_at DESC")
  end

  def dashboard
    @purchases = Order.all.where(buyer: current_user).order("created_at DESC")
    @purchases_num = @purchases.group('date(created_at)').count   
    @purchases_amount = @purchases.group('date(created_at)').sum(:price)



    @orders = Order.all.where(seller: current_user).order("created_at DESC")    
    @orders_num = @orders.group('date(created_at)').count   
    @orders_amount = @orders.group('date(created_at)').sum(:price)


  end



  # GET /orders/1
  # GET /orders/1.json

  # GET /orders/new
  def new
    @order = Order.new
    @listing = Listing.find(params[:listing_id])
  end

  
  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)
    @listing = Listing.find(params[:listing_id])
    @seller = @listing.user
    @order.seller_id = @seller.id

    @order.listing_id = @listing.id
    @order.buyer_id = current_user.id
    @order.price = @listing.price



    respond_to do |format|
      if @order.save

        # Tell the UserMailer to send a welcome email after save
        UserMailer.welcome_email(@seller).deliver_later

        #format.html { redirect_to root_url, notice: 'Order was successfully created.' }
        format.html { redirect_to new_transaction_path, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:address, :city, :state)
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<%= form_for([@listing, @order]) do |f| %>
  <% if @order.errors.any? %>
    <div id="error_explanation" class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <h4><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h4>
      <ul>
      <% @order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="container" >
   <div class="form-group">
    <%= f.label :address %>
    <%= f.text_field :address, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :city %>
    <%= f.text_field :city, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :state %>
    <%= f.text_field :state, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit "Complete Order", class: "btn btn-success" %>
  </div>
</div>





<% end %>

app/views/orders/dashboard.html.erb
<%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>


<div class="container-fluid">

<div class="row">

<div class="col-md-6">

  <h5> <div class="text-center"> Purchase history </div></h5>

<%= line_chart [
  { name: "購入数", data: @purchases_num },
  { name: "購入額", data: @purchases_amount }
] %>

<br>

  <table class="table table-striped table-bordered">
    <tr>
      <th class="center">Item name</th>
      <th class="center">Price</th>
      <th class="center">Company</th>
      <th class="center">Date purchased</th>
    </tr>

  <% @purchases.each do |purchase| %>
      <tr>
        <td><%= link_to purchase.listing.name, listing_path(purchase.listing) %></td>
        <td><%= number_to_currency(purchase.listing.price) %></td>
        <td><%= purchase.seller.name %></td>
        <td><%= purchase.created_at.strftime("%B %-d, %Y") %>  </td>
      </tr>
    <% end %>
  </table>
</div>

<div class="col-md-6">

   <h5> <div class="text-center"> Sold history</div> </h5>


<%= line_chart [
  { name: "販売数", data: @orders_num },
  { name: "販売額", data: @orders_amount }
] %>

<br>

  <table class="table table-striped table-bordered">
    <tr>
      <th class="center"> Regerence # </th>
      <th class="center">Item name</th>
      <th class="center">Price</th>
      <th class="center">Buyer name</th>
      <th class="center">Date Sold</th>
    </tr>

  <% @orders.each do |order| %>
      <tr>
        <td><%= order.id %></td>
        <td><%= link_to order.listing.name, listing_path(order.listing) %></td>
        <td><%= number_to_currency(order.listing.price) %></td>
        <td><%= order.buyer.name %></td>
        <td><%= order.created_at.strftime("%B %-d, %Y") %>  </td>
      </tr>
    <% end %>
  </table>
</div>



</div>
</div>


<br>
<% if user_signed_in? %>
<%= link_to 'New Listing', new_listing_path %>
<% end %>

app/views/orders/new.html.erb
<h1>New Order</h1>

<%= render 'form' %>


<%= link_to 'Back', listing_orders_path %>

app/views/orders/sales.html.erb
<div class="container-fluid">

<div class="row">

 <div class="text-center"> Selling </div>

<table class="table table-striped table-bordered">
  <tr>
    <th class="center">Item</th>
    <th class="center">Name</th>
    <th class="center">Price</th>
    <th class="center">Customer</th>
    <th class="center">Date Sold</th>
  </tr>

<% @orders.each do |order| %>
    <tr>
      <td><%= image_tag order.listing.image_url(:thumb) %></td>
      <td><%= order.listing.name %></td>
      <td><%= number_to_currency(order.listing.price) %></td>
      <td><%= order.buyer.name %></td>
      <td><%= order.created_at.strftime("%B %-d, %Y") %>  </td>
    </tr>
  <% end %>
</table>





<br>
<% if user_signed_in? %>
<%= link_to 'New Listing', new_listing_path %>
<% end %>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Address:</strong>
  <%= @order.address %>
</p>

<p>
  <strong>City:</strong>
  <%= @order.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @order.state %>
</p>

<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>