config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  
  resources :transactions
  resources :listings do
  resources :orders, only: [:new, :create]  
  end  

  get 'users/auth/facebook/callback', to: "sessions#create"
  get 'users/auth/facebook/signout', to: "sessions#destroy"

  get 'pages/about'

  get 'pages/contact'
  get 'sales' => "orders#sales"
  get 'purchases' => "orders#purchases"
  get 'dashboard' => "orders#dashboard"
  get 'pages/home'
  get 'seller' => "listings#seller"

 get 'get_info', to: 'books#get_info', path: "/books/new/get_info"

  root 'listings#index'

end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/listings/"><i class="fa fa-exchange"></i>SHARIENDS</a>
    </div>


    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      
     
      <ul class="nav navbar-nav navbar-left">

        <li><%= link_to "About", pages_about_path %> </li>
        <li><%= link_to "Home", pages_home_path %> </li>
 
</ul>

      <ul class="nav navbar-nav navbar-right">


                <% if user_signed_in? %>
                                
                <li class="dropdown">
                      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                       Seller account
                      <span class="caret"></span>
                      </button>
                      <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">

                                    <li><%= link_to "Seller page", seller_path %> </li>
                                     </li>
                     </ul>
                </li>


<li class="dropdown">
                      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                       <%= current_user.name %>
                      <span class="caret"></span>
                      </button>
                      <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">

                                    <li><%= link_to "Setting", edit_user_registration_path %> </li>
                                    <li><%= link_to "Dashboard", dashboard_path %> </li>
                                    <li><%= link_to "Log out", destroy_user_session_path, method: :delete %> </li>
                     </ul>
                </li>



                <% else %>
                <li><%= link_to "Sign-up", new_user_registration_path %> </li>
                <li><%= link_to "Log-in", new_user_session_path %> </li>
                 <% end %> 

      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sharedemo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header' %>


<div class= "container" >
<% flash.each do |name, msg| %>
    <% if msg.is_a?(String) %>
      <div class="alert alert-<%= name == :notice ? "success" : "danger" %> alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      </div>
    <% end %>
  <% end %>

</div>
<%= yield %>

</body>
</html>